---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-SmartOS.yml
  when: (ansible_os_family == 'Solaris') and (ansible_distribution == 'SmartOS')
